### PR TITLE
Add custom HTTP headers

### PR DESCRIPTION
**Pull request by domenic**
This should fix the broken build for whatwg/misc-server

### CODE REVIEW

**Review by annevk — COMMENTED** [review]
Can we add a comment both here and in misc-server to keep these two places synchronized? I think we hit this with participate as well and did the same thing in case of future updates.

**Comment by domenic** [comment]
Well, eventually misc-server will not be specifying any headers (except in the tests), but I guess we can do that for now.

**Comment by annevk** [comment]
I guess something will still own the configuration though, right? So I guess we'd have to update some pointers at that point or keep misc-server as the central point of coordination.

**Comment by domenic** [comment]
Yeah, there will be some repo that sets headers for the static hosting, although it's not yet clear what that'll look like since static hosting is a surprisingly hard problem...

**Review by annevk — APPROVED** [review]

**Comment by domenic** [comment]
This appears not to have worked. That's what I get for not testing locally...

**Comment by annevk** [comment]
Oh, it matches the documentation as far as I can tell. That's frustrating.

**Pull request merged**
